import { MessageStatus } from '.';
import { Link } from '..';
import { dateLocaleRo } from '../../functions';

const MessagesTableRow = ({ number, _id, email, dateReceived, assignedPerson, status }) => {
  return (
    <tr className="whitespace-nowrap border text-sm text-gray-700">
      <td className="sm:p-4 p-2">#{number}</td>
      <td className="sm:p-4 p-2">
        <div className="inline-flex">
          <Link
            href="/admin/tickets/[uuid]"
            as={`/admin/tickets/${_id}`}
            className="hover:underline p-2 -m-2"
          >
            <h4 className="font-medium text-gray-800 hover:text-black">{email}</h4>
          </Link>
        </div>
      </td>
      <td className="sm:p-4 p-2">{dateLocaleRo(dateReceived)}</td>
      <td className="sm:p-4 p-2">{assignedPerson?.name || ''}</td>
      <td className="sm:p-4 w-20 p-2">
        <MessageStatus status={status} />
      </td>
    </tr>
  );
};

export default MessagesTableRow;
/* auto-generated by robocode v0.4.3 */
