import React from 'react';

const MessagesTableHeader = () => {
  return (
    <thead className="bg-gray-200">
      <tr className="text-sm">
        <th className="sm:p-4 p-2 py-4 w-8 sm:w-10">Tichet</th>
        <th className="sm:p-4 p-2 w-2/3 sm:w-auto cursor-pointer py-2">Email</th>
        <th className="sm:p-4 p-2">Data primirii</th>
        <th className="sm:p-4 p-2">Persoană alocată</th>
        <th className="sm:p-4 p-2">Status</th>
      </tr>
    </thead>
  );
};

export default MessagesTableHeader;
/* auto-generated by robocode v0.4.3 */
