import { TicketCardError, TicketCardLoading, TicketCardSuccess } from '.';
import { useQuery } from '../../hooks';

const TicketCard = ({ uuid }) => {
  const { data, status, refetch } = useQuery(`/admin/tickets/${uuid}`);

  return (
    <>
      {status === 'loading' && <TicketCardLoading />}
      {status === 'error' && <TicketCardError />}
      {status === 'success' && <TicketCardSuccess {...data} refetch={refetch} />}
    </>
  );
};

export default TicketCard;
/* auto-generated by robocode v0.4.3 */
