import { Bone } from '@components';
import { Textarea } from '@components/Fields';

const TicketCardLoading = () => {
  return (
    <article className="gap-6 md:grid md:grid-cols-3 flex flex-col-reverse">
      <div className="flex flex-col col-span-2 p-6 bg-white rounded-md border">
        <section className="flex flex-col gap-4 ">
          <div className="flex gap-2 items-center mb-4">
            <Bone type="loading" extraClass="w-2/3" />
          </div>
          <div>
            <p className="font-medium mb-2 text-lg">
              De ce crezi că ai/te confrunți cu această problemă/situație
            </p>
            <Bone type="loading" extraClass="w-2/3 mb-2" />
            <Bone type="loading" extraClass="w-1/3 mb-2" />
          </div>
          <div>
            <p className="font-medium mb-2 text-lg">Cum ar fi viața ta în lipsa acestei probleme</p>
            <Bone type="loading" extraClass="w-2/3 mb-2" />
            <Bone type="loading" extraClass="w-1/3 mb-2" />
          </div>
          <div>
            <p className="font-medium mb-2 text-lg">Mesaj</p>
            <Bone type="loading" extraClass="w-full mb-2" />
            <Bone type="loading" extraClass="w-full mb-2" />
            <Bone type="loading" extraClass="w-full mb-2" />
            <Bone type="loading" extraClass="w-1/3 mb-2" />
          </div>
          <p className="font-medium text-lg">Răspunsul tău</p>
        </section>
        <Textarea disabled />
        <div className="flex flex-col sm:flex-row sm:justify-end mt-3">
          <button
            disabled
            className="w-full sm:w-fit button flex pl-5 pr-5 sm:pr-2 rounded-full gap-6 items-center full bg-indigo-500 border-none text-white"
          >
            <span className="mx-auto uppercase">Trimite</span>
            <div className="hidden sm:flex justify-center items-center gap-2 w-3 h-3 p-3 bg-indigo-400 rounded-full">
              <i className="text-xs fa-solid fa-arrow-right"></i>
            </div>
          </button>
        </div>
      </div>
      <div className="flex flex-col rounded-md border h-min bg-white">
        <div className="flex justify-between items-center py-4 border-b border-gray-200 px-4">
          <div className="flex flex-col gap-2 items-center">
            <h2 className="font-medium text-lg flex items-center">
              Tichet # <Bone type="loading" extraClass="w-10 ml-2" />
            </h2>
          </div>
          <Bone type="loading" extraClass="w-14" />
        </div>
        <div className="flex flex-col gap-5 border-b border-gray-200 p-4">
          <div className="hidden xl:flex-row flex-col flex xl:items-center xl:gap-5 gap-1 -mb-2">
            <span className="font-medium xl:whitespace-nowrap">Persoană desemnată: </span>
          </div>
          <div className="flex items-center font-medium gap-4">
            <i className="text-gray-500 text-base fa-solid fa-circle-user"></i>
            <Bone type="loading" extraClass="w-2/3 mb-2" />
          </div>
          <div className="flex items-center font-medium text-gray-500 gap-4">
            <i className="fa-solid fa-envelope"></i>
            <Bone type="loading" extraClass="w-2/3 mb-2" />
          </div>
          <div className="flex items-center font-medium text-gray-500 gap-4">
            <i className="fa-solid fa-calendar-days"></i>
            <Bone type="loading" extraClass="w-1/3 mb-2" />
          </div>
          <div className="flex hidden items-center gap-4">
            <span className="font-medium">Ultima actualizare: </span>
            <Bone type="loading" extraClass="w-2/3 mb-2" />
          </div>
        </div>
        <div className="p-4 w-full lg:w-2/3 ">
          <Bone type="loading" extraClass="w-full mb-2" />
        </div>
      </div>
    </article>
  );
};

export default TicketCardLoading;
/* auto-generated by robocode v0.4.3 */
