import { Bone } from '..';

const UserProfileLoading = () => {
  return (
    <div className="flex flex-col items-center gap-6 bg-white rounded-xl shadow p-8">
      <div className="flex flex-col items-center">
        <div className="w-16 h-16 mb-2 bg-indigo-400 rounded-full flex justify-center items-center text-white font-bold text-3xl animate-pulse" />
        <div className="flex flex-col items-center gap-1">
          <Bone type="loading" extraClass="w-32 mb-1" />
          <Bone type="loading" extraClass="w-20 mb-1" />
        </div>
      </div>
      <div className="flex flex-col divide-y-2">
        <div className="flex items-center py-2">
          <i className="text-indigo-400 fa-solid fa-envelope w-7"></i>
          <Bone type="loading" extraClass="w-full" />
        </div>
        <div className="flex items-center py-2">
          <i className="text-indigo-400 fa-solid fa-user-check w-7"></i>
          <div className="flex gap-1">
            <p>Membru din </p>
            <Bone type="loading" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default UserProfileLoading;
/* auto-generated by robocode v0.4.3 */
