import { ProfileActions, UserProfileError, UserProfileLoading, UserProfileSuccess } from '.';
import { useQuery } from '../../hooks';

const UserProfile = () => {
  const { data, status } = useQuery(`/admin/profile`);

  return (
    <div className="flex flex-col gap-8">
      <img
        className="sm:object-cover hidden md:block object-center
        rounded-t-xl w-full sm:h-72 h-64"
        src="/images/profile-cover.svg"
        alt="profile-cover"
      />
      <div className="sm:grid sm:grid-cols-3 flex flex-col gap-4 px-4 sm:px-8 sm:-mt-44">
        {status === 'loading' && <UserProfileLoading />}
        {status === 'error' && <UserProfileError />}
        {status === 'success' && <UserProfileSuccess data={data} />}
        <ProfileActions uuid={data?._id} />
      </div>
    </div>
  );
};

export default UserProfile;
/* auto-generated by robocode v0.4.3 */
