import { UserDetailsCard } from '.';

const UserProfileSuccess = ({ data }) => {
  return <UserDetailsCard {...data} />;
};

export default UserProfileSuccess;
/* auto-generated by robocode v0.4.3 */
